
export const CLICK_INPUT_VALUE = 'CLICK_INPUT_VALUE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CLICK_BTN_ADD = 'CLICK_BTN_ADD';
export const CLICK_ITEM_DEL = 'CLICK_ITEM_DEL';



